### ISSUE TITLE
Emotes no work

### ISSUE THREAD

**Issue by theboy6545** [WaspStation/WaspStation-1.0#595] opened 2020-11-27 17:51 UTC
Issue reported from  Round ID: 1979 (BoomerStation - RP)

Reporting client version: 513.1535

When I try a *spin or a *speen, I just say it, and I don't do the action

**Comment by MarkSuckerberg** [comment] 2020-11-27 18:09
Caused by #593, should be fixed on round restart.

**Comment by Jack7D1** [comment] 2020-12-01 01:23
aaaa close issue

**Comment by MarkSuckerberg** [comment] 2020-12-01 01:28
aeiou

**Closed by MarkSuckerberg** 2020-12-01 01:28 UTC
