### ISSUE TITLE
[BUG] Bridge Announcements gives wrong ID

### ISSUE THREAD

**Issue by Superyodeler** [WaspStation/WaspStation-1.0#296] opened 2020-06-22 02:51 UTC
Bridge announcements signature doesn't respect your currently worn ID.

**Comment by Maldaris** [comment] 2020-07-14 16:25
Necrobumping this, but I had a question before I dived into this issue, Does it respect the ID you logged into the terminal with?

**Comment by untrius** [comment] 2020-09-01 01:29
It looks like it takes the name from the character's name.
priority_announce.dm:
![image](https://user-images.githubusercontent.com/7697956/91783985-4f51c680-ebc7-11ea-82b5-f09c5a81f93f.png)

From testing it seems to take the character name, then say "(as [name on id])" if it's not the same, then list the job assigned to the character.  In this example Dummy B is a HoS id.
![image](https://user-images.githubusercontent.com/7697956/91784316-385fa400-ebc8-11ea-8297-85772460d9a2.png)

What's the desired behavior?  Have it list the name and job of the equiped id?

**Comment by untrius** [comment] 2020-09-01 04:30
This seems to be functioning as intended, as stated in PR #44

**Closed** 2020-11-13 06:31 UTC
Labels: wontfix
